name: Update Contributor Rank Badge

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-rank-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update rank badge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python check_repo_rank.py

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "actions@github.com"
        git add README.md
        git commit -m "Update contributor rank badge"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
